.if .not .defined( NGIN_CONFIG_INC_INCLUDED )
NGIN_CONFIG_INC_INCLUDED = 1

ngin_cfg_MapData_viewWidth      = ${ngin_cfg_MapData_viewWidth}
ngin_cfg_MapData_viewHeight     = ${ngin_cfg_MapData_viewHeight}
ngin_cfg_MapData_attrViewWidth  = ${ngin_cfg_MapData_attrViewWidth}
ngin_cfg_MapData_attrViewHeight = ${ngin_cfg_MapData_attrViewHeight}

ngin_cfg_SpriteRenderer_offsetX = ${ngin_cfg_SpriteRenderer_offsetX}
ngin_cfg_SpriteRenderer_offsetY = ${ngin_cfg_SpriteRenderer_offsetY}

ngin_cfg_DebugDraw_offsetX = ${ngin_cfg_DebugDraw_offsetX}
ngin_cfg_DebugDraw_offsetY = ${ngin_cfg_DebugDraw_offsetY}

.endif
